export const STRINGS = {
  en: {
    title: "Crisis Support & Safety",
    emergencyBanner: "If you are in immediate danger, call emergency services now:",
    notAlone: "You're not alone. Help is available 24/7.",
    immediateHelp: "Immediate Help",
    copingTools: "Coping Tools",
    safetyPlan: "Safety Plan",
    resources: "Resources",
    settings: "Settings",
    callEmergency: "Call Emergency",
    callCrisis: "Call Crisis Line",
    textCrisis: "Text Crisis Line",
    copyNumber: "Copy Number",
    shareContact: "Share with Trusted Contact",
    findCenter: "Find Local Center",
    breathing: "4-7-8 Breathing",
    breathingDesc: "A calming breathing technique",
    grounding: "5-4-3-2-1 Grounding",
    groundingDesc: "Focus on your senses to stay present",
    quickTips: "Quick Coping Tips",
    breathingInhale: "Inhale 4",
    breathingHold: "Hold 7",
    breathingExhale: "Exhale 8",
    start: "Start",
    pause: "Pause",
    reset: "Reset",
    groundingPrompt: "Name items you notice:",
    see5: "5 things you can see",
    touch4: "4 things you can touch",
    hear3: "3 things you can hear",
    smell2: "2 things you can smell",
    taste1: "1 thing you can taste",
    warningSignsTitle: "Personal Warning Signs",
    warningSignsDesc: "What tells you that you might be struggling?",
    copingStrategiesTitle: "Coping Strategies",
    copingStrategiesDesc: "What helps you feel better?",
    supportContactsTitle: "People to Contact",
    supportContactsDesc: "Friends, family, or trusted people",
    professionalsTitle: "Professional Contacts",
    professionalsDesc: "Therapists, doctors, counselors",
    environmentTitle: "Environment Safety",
    environmentDesc: "Steps to make your space safer",
    emergencyContactsTitle: "Emergency Contacts",
    emergencyContactsDesc: "Crisis lines and emergency numbers",
    saveLocal: "Save Locally",
    exportPlan: "Export Plan",
    printPlan: "Print Plan",
    clearPlan: "Clear Plan",
    privacyNotice:
      "Your safety plan is stored locally on your device unless you choose to export it.",
    country: "Country",
    language: "Language",
    copiedToClipboard: "Copied to clipboard",
    planSaved: "Safety plan saved locally",
    planExported: "Safety plan exported",
    planCleared: "Safety plan cleared",
    shareMessage:
      "I'm going through a difficult time and could use your support. Here are some crisis resources:",
    quickCopingTips: [
      "Take slow, deep breaths",
      "Drink a glass of cold water",
      "Call or text someone you trust",
      "Listen to calming music",
      "Go for a short walk if safe",
      "Write down three things you're grateful for",
    ],
  },
  es: {
    title: "Apoyo en Crisis y Seguridad",
    emergencyBanner:
      "Si estás en peligro inmediato, llama a servicios de emergencia ahora:",
    notAlone: "No estás solo. La ayuda está disponible 24/7.",
    immediateHelp: "Ayuda Inmediata",
    copingTools: "Herramientas de Afrontamiento",
    safetyPlan: "Plan de Seguridad",
    resources: "Recursos",
    settings: "Configuración",
    callEmergency: "Llamar Emergencia",
    callCrisis: "Llamar Línea de Crisis",
    textCrisis: "Enviar Texto a Crisis",
    copyNumber: "Copiar Número",
    shareContact: "Compartir con Contacto de Confianza",
    findCenter: "Encontrar Centro Local",
    breathing: "Respiración 4-7-8",
    breathingDesc: "Una técnica de respiración calmante",
    grounding: "Conexión a Tierra 5-4-3-2-1",
    groundingDesc: "Enfócate en tus sentidos para mantenerte presente",
    quickTips: "Consejos Rápidos",
    breathingInhale: "Inhalar 4",
    breathingHold: "Mantener 7",
    breathingExhale: "Exhalar 8",
    start: "Iniciar",
    pause: "Pausar",
    reset: "Reiniciar",
    groundingPrompt: "Nombra elementos que notes:",
    see5: "5 cosas que puedes ver",
    touch4: "4 cosas que puedes tocar",
    hear3: "3 cosas que puedes escuchar",
    smell2: "2 cosas que puedes oler",
    taste1: "1 cosa que puedes saborear",
    country: "País",
    language: "Idioma",
    copiedToClipboard: "Copiado al portapapeles",
    planSaved: "Plan de seguridad guardado localmente",
    planExported: "Plan de seguridad exportado",
    planCleared: "Plan de seguridad borrado",
    shareMessage:
      "Estoy pasando por un momento difícil y podría usar tu apoyo. Aquí hay algunos recursos de crisis:",
    quickCopingTips: [
      "Respira lenta y profundamente",
      "Bebe un vaso de agua fría",
      "Llama o envía un mensaje a alguien de confianza",
      "Escucha música relajante",
      "Sal a caminar si es seguro",
      "Escribe tres cosas por las que estés agradecido",
    ],
  },
  hi: {
    title: "संकट सहायता और सुरक्षा",
    emergencyBanner:
      "यदि आप तत्काल खतरे में हैं, तो अभी आपातकालीन सेवाओं को कॉल करें:",
    notAlone: "आप अकेले नहीं हैं। सहायता 24/7 उपलब्ध है।",
    immediateHelp: "तत्काल सहायता",
    copingTools: "सामना करने के उपकरण",
    safetyPlan: "सुरक्षा योजना",
    resources: "संसाधन",
    settings: "सेटिंग्स",
    callEmergency: "आपातकालीन कॉल करें",
    callCrisis: "संकट हेल्पलाइन कॉल करें",
    textCrisis: "संकट हेल्पलाइन को टेक्स्ट करें",
    copyNumber: "नंबर कॉपी करें",
    shareContact: "विश्वसनीय संपर्क के साथ साझा करें",
    findCenter: "स्थानीय केंद्र खोजें",
    breathing: "4-7-8 श्वास",
    breathingDesc: "एक शांत करने वाली श्वास तकनीक",
    grounding: "5-4-3-2-1 ग्राउंडिंग",
    groundingDesc: "वर्तमान में रहने के लिए अपनी इंद्रियों पर ध्यान दें",
    quickTips: "त्वरित सुझाव",
    breathingInhale: "सांस लें 4",
    breathingHold: "रोकें 7",
    breathingExhale: "छोड़ें 8",
    start: "शुरू करें",
    pause: "रोकें",
    reset: "रीसेट करें",
    groundingPrompt: "उन चीजों का नाम बताएं जिन्हें आप नोटिस करते हैं:",
    see5: "5 चीजें जो आप देख सकते हैं",
    touch4: "4 चीजें जिन्हें आप छू सकते हैं",
    hear3: "3 चीजें जो आप सुन सकते हैं",
    smell2: "2 चीजें जिन्हें आप सूंघ सकते हैं",
    taste1: "1 चीज़ जिसका आप स्वाद ले सकते हैं",
    country: "देश",
    language: "भाषा",
    copiedToClipboard: "क्लिपबोर्ड पर कॉपी किया गया",
    planSaved: "सुरक्षा योजना स्थानीय रूप से सहेजी गई",
    planExported: "सुरक्षा योजना निर्यात की गई",
    planCleared: "सुरक्षा योजना साफ़ की गई",
    shareMessage:
      "मैं एक कठिन समय से गुजर रहा हूं और आपके समर्थन का उपयोग कर सकता हूं। यहां कुछ संकट संसाधन हैं:",
    quickCopingTips: [
      "धीमी, गहरी सांस लें",
      "एक गिलास ठंडा पानी पिएं",
      "किसी भरोसेमंद व्यक्ति को कॉल या टेक्स्ट करें",
      "शांत संगीत सुनें",
      "यदि सुरक्षित है तो थोड़ी देर टहलने जाएं",
      "तीन चीजें लिखें जिनके लिए आप आभारी हैं",
    ],
  },
} as const;

export const COUNTRIES = {
  IN: {
    code: "IN",
    name: "India",
    emergencyNumber: "112",
    crisisPhone: "9152987821",
    crisisTextKeyword: "Not available",
    crisisTextNumber: "",
    smsBody: "",
    links: [
      { name: "AASRA", url: "http://www.aasra.info" },
      { name: "Vandrevala Foundation", url: "https://www.vandrevalafoundation.com" },
    ],
  },
  OTHER: {
    code: "OTHER",
    name: "International",
    emergencyNumber: "Local emergency number",
    crisisPhone: "See resources below",
    crisisTextKeyword: "Varies by country",
    crisisTextNumber: "",
    smsBody: "",
    links: [
      { name: "Find a Helpline (IASP)", url: "https://findahelpline.com" },
      { name: "International Association for Suicide Prevention", url: "https://www.iasp.info" },
    ],
  },
} as const;